// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_production.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2qUszPSaijOKMfp-0hZXtB17thD7mxBs',
    appId: '1:639907974997:web:e40e0298b0232e7f99a9dc',
    messagingSenderId: '639907974997',
    projectId: 'flutter-course-production',
    authDomain: 'flutter-course-production.firebaseapp.com',
    storageBucket: 'flutter-course-production.appspot.com',
    measurementId: 'G-QG23R8DR4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4U8EezzwQaqpgRMH98nHldiB27xQPBxQ',
    appId: '1:639907974997:android:5909cdaf21c5de7699a9dc',
    messagingSenderId: '639907974997',
    projectId: 'flutter-course-production',
    storageBucket: 'flutter-course-production.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4aBclwVJNl9DcIHMn4YTwACFKsFLJK9c',
    appId: '1:639907974997:ios:43352b8a58505b7d99a9dc',
    messagingSenderId: '639907974997',
    projectId: 'flutter-course-production',
    storageBucket: 'flutter-course-production.appspot.com',
    iosBundleId: 'com.cotr.flutterCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4aBclwVJNl9DcIHMn4YTwACFKsFLJK9c',
    appId: '1:639907974997:ios:914d74dbaea0a9dd99a9dc',
    messagingSenderId: '639907974997',
    projectId: 'flutter-course-production',
    storageBucket: 'flutter-course-production.appspot.com',
    iosBundleId: 'com.cotr.flutterCourse.RunnerTests',
  );
}
