name: Deploy to Firebase Hosting on merge

'on':
  push:
    branches:
      - test

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - staging
          - production
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.6'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build web --dart-define=environment=${{ matrix.env }}
        if: github.ref == 'refs/heads/${{ matrix.env }}'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_${{ matrix.env }} }}'
          FIREBASE_CLI_EXPERIMENTS: webframeworks
          channelId: live
          projectId: ${{ secrets.PROJECT_ID_${{ matrix.env }} }}
        if: github.ref == 'refs/heads/${{ matrix.env }}'
